### ISSUE TITLE
Setup problem v2.0.1

### ISSUE THREAD

**Issue by pjmpessers** [loqed-nl/homey-app#11]
Hello.

Thank you for your app. But i stumbled over a problem when i want to install a loqed with app version 2.0.1. It gives: "socked not defined". Switching back to v1.4.1 and i could install it asking for my password and login name. After that i could install v2.0.1 again. So it is a setup problem only.

**Comment by BertvanHoekelen** [comment]
That's correct. 2.0.1 is still in test and not ready for production. It's a start with refactoring the app to use the new apps sdk and is prework for new features that will be added. For now I will unpublish the app from the store so that nobody will install it again, thanks!

**Comment by pjmpessers** [comment]
Okay. I understand. Thanks. And again thanks for the app.

**Comment by BertvanHoekelen** [comment]
I just release a new version that resolves this issue. You can find it at https://homey.app/nl-nl/app/com.loqed.touch-smart-lock/LOQED/test/
