### ISSUE TITLE
await webhook response

### ISSUE THREAD

**Issue by WeeJeWel** [loqed-nl/homey-app#12]
I see the capabilities always resolve. It's better to await the result in your capability listener. This way the user can see when something went wrong, and the new capability's state won't be saved.

**Comment by WeeJeWel** [comment]
FYI I recommend `node-fetch` as library for Promise-based HTTP.

**Comment by BertvanHoekelen** [comment]
Thanks! Will change this behaviour when the new API is available.

**Comment by BertvanHoekelen** [comment]
Is resolved in https://github.com/loqed-nl/homey-app/releases/tag/2.0.3
