### ISSUE TITLE
Missing unlock and open as action card

### ISSUE THREAD

**Issue by mruiter** [loqed-nl/homey-app#13]
It’s nice that I can unlock the door .
But it’s not a real action one uses a lot 

I’m missing the unlock and open that I can use in flows with disabling alarm with keyfob and presence is homey as a verification 
All other locks have this why did the locked app not implement this

**Comment by BertvanHoekelen** [comment]
You are able to open, unlock and lock. In the "Then" section of creating a flow, you have to select `Change lock state` there you have `open`, `unlock` and `lock`.
