### ISSUE TITLE
install

### ISSUE THREAD

**Issue by CHPhilu** [loqed-nl/homey-app#14]
Hello 
I cant install the adapter. Exit with code 25

**Comment by CHPhilu** [comment]
$ iobroker url https://github.com/loqed-nl/homey-app.git --host raspberrypi --debug

install loqed-nl/homey-app#0b940a03c90223a36e32bcad6ed42a56df94dbb8

NPM version: 6.14.15npm install loqed-nl/homey-app#0b940a03c90223a36e32bcad6ed42a56df94dbb8 --prefix "/opt/iobroker" (System call)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ com.loqed.touch-smart-lock@1.0.0updated 1 package in 31.745s

105 packages are looking for funding run `npm fund` for details

host.raspberrypi Cannot install loqed-nl/homey-app#0b940a03c90223a36e32bcad6ed42a56df94dbb8: 0

ERROR: Process exited with code 25

**Comment by BertvanHoekelen** [comment]
It looks like your trying to install this app in iobroker. This app is only for [Homey](https://homey.app/nl-nl/).
