### ISSUE TITLE
Flow not working

### ISSUE THREAD

**Issue by eeckelaertyannick** [loqed-nl/homey-app#16]
Hi,

I put in a flow when a person opens the door whit his code ore whit the locked app. The user is detected en status of the user is home.

Flow: https://homey.app/f/wT3kbX

But this dos not work. My girlfriend opent the door whit the app. En anger status was still away. En this triggers the alarm.

Maybe this is because I online say in the and flow "if unlocked" maybe schould come a way to say "if opens" 
Because she dos not unlock it first she opens it.

Can u advice? Maybe I schould change the flow ore something did not work.

Thx!

**Comment by BertvanHoekelen** [comment]
You should use the logic variable LOCK_STATE in the "and" section. This can be OPEN, DAYLOCK, NIGHTLOCK.

See example: https://homey.app/nl-nl/flow/5dsTtX/
