### ISSUE TITLE
Loqed extra flow chart

### ISSUE THREAD

**Issue by eeckelaertyannick** [loqed-nl/homey-app#17]
Please add extra flow chat. Now in the "if" we can only say locked ore unlocked. Would be great if you add if the Locke is opend than...

**Comment by eeckelaertyannick** [comment]
?

**Comment by BertvanHoekelen** [comment]
In the new version there is a tigger card that does exactly this. You can try it out: https://homey.app/a/com.loqed.touch-smart-lock/test/
