### ISSUE TITLE
Homey not opening lock

### ISSUE THREAD

**Issue by m3ngi3** [loqed-nl/homey-app#18]
Any issues about open action not opening lock anymore?

I have a flow which has been working fine since the beginning to automatically open the door when Ring door bell is triggered (with other checks like being home and being unlocked).

Action to Lock and Unlock works from Homey, but Open does not anymore...

**Comment by janpi80** [comment]
Same issue here. May 9th was an homey update, that could have something to do with it.
https://firmware.athom.com
Today they have a new firmware release, maybe this solves it.

**Comment by BertvanHoekelen** [comment]
For me it's still working on the "regular" version. But it's indeed happening on the "test" version in the app store, so try to switch back to the regular version. There is no way for me to remove the app from testing. I will need to look into the app later.

**Comment by janpi80** [comment]
I have the regular version. Updating to homey 7.4.2 worked though. The lock works again.

**Comment by m3ngi3** [comment]
An update

Loqed App by default has two options for a lock:
![image](https://user-images.githubusercontent.com/47530580/184599060-28253239-ab9f-4e6e-873c-22c987e5bf87.png)

Homey App has three options for a lock:
![image](https://user-images.githubusercontent.com/47530580/184599107-55164703-9f94-407c-80b4-c1f1543abda9.png)

I have been using the Ontgrendel (Unlock) option in flows to unlock (NOT OPEN) the door in the morning around 7:30 if Homey knows I am at home. This is useful so we do not have to unlock the door manually (and wait) a few seconds before someone can open the door -->especially useful with impatient wives and children...

Since a few days I have been getting the Loqed emails that the lock could not open:
![image](https://user-images.githubusercontent.com/47530580/184599408-26d5c7d1-ecbc-4d42-8ef5-166b42533b77.png)

Usually these were incidents on a very small frequency and I could ignore them... but in the last 5 days there have been 2 days where the door was opened (not just unlocked)... you can imagine this is undeasired right??

I was still on Experimental / Beta so 

1. I just reverted back to the general available version of the Homey App:
![image](https://user-images.githubusercontent.com/47530580/184599746-c76fe1ac-781d-46cb-aad9-0b8b54c5192d.png)
2. I restarted the lock using the 9V battery way of work
3. I recalibrated the lock

Will update when more info known.

**Comment by BertvanHoekelen** [comment]
This should be fixed in the new version. https://homey.app/a/com.loqed.touch-smart-lock/test/
