### ISSUE TITLE
Loqed Homey - Using Zone Activity

### ISSUE THREAD

**Issue by RoccoWijnsma** [loqed-nl/homey-app#19]
Would be great if my loqed could trigger the zone activity to ACTIVE for one minute if the door is opened. And of course with the option to turn this off in advanced settings. 

For example, when someone enters the Hallway Zone with the front door, Loqed detect this, making the Zone active. When the door is closed again (after some time), the zone will become inactive.
![image](https://user-images.githubusercontent.com/6980236/202310277-a10ad757-fadd-4c8f-963d-52a86b795d7e.png)

**Comment by BertvanHoekelen** [comment]
Good suggestion! I'm working on a new version and can investigate if this is possible. I'm not sure Athom support triggering zone's using the API.

**Comment by BertvanHoekelen** [comment]
Unfortunately this is not possible with the Homey SDK. Maybe you can ask Athom if they are planning on the ability of exposing this functionality
