### ISSUE TITLE
Opening lock with remote switch and then locking with door sensor will be ignored.

### ISSUE THREAD

**Issue by pjmpessers** [loqed-nl/homey-app#21]
Hello.

I went to HP2023 so i needed to install the new loqed app. I didn't want to use this app, because when i open the lock with a remote switch and i walk outside the closing of the lock will be ignored.

Is this possible to update when it sees that it goes from opening to closing or closing to opening will be executed?

Thanks for the app.

**Comment by BertvanHoekelen** [comment]
This should be fixed in the new version. https://homey.app/a/com.loqed.touch-smart-lock/test/
