### ISSUE TITLE
Opening door in "then" flowcard is ignored

### ISSUE THREAD

**Issue by pjmpessers** [loqed-nl/homey-app#24]
I installed a second device to get the battery conditions. In the loqed device i see the battery condition. But i can't open the door in the "then"-flowcard resulting in a red exclamation mark. I can only lock or unlock.

**Comment by BertvanHoekelen** [comment]
Thanks for reporting this! This should be fixed in version v3.3.0.

**Comment by pjmpessers** [comment]
Thank you. Great to hear. 👍🏻
