### ISSUE TITLE
[Request] add slot status in then, slot status changed in if

### ISSUE THREAD

**Issue by jvdmeulen** [loqed-nl/homey-app#25]
Please add these options

![Capture 2023-11-18 at 11 38 12@2x](https://github.com/loqed-nl/homey-app/assets/129403/6a79ed06-cb7d-4a18-9802-efedcf9026ec)

**Comment by XeroxQ** [comment]
Do the new Tags suffice?
![image](https://github.com/loqed-nl/homey-app/assets/43435060/15338596-233b-4954-b575-9fe71a860a49)

And the new When cards?
![image](https://github.com/loqed-nl/homey-app/assets/43435060/0e194c0a-66a2-4b59-b94d-26095a46d88f)
