### ISSUE TITLE
Request: would be nice have a flow cards showing the Battery- and Bridge status 

### ISSUE THREAD

**Issue by Petclaud** [loqed-nl/homey-app#26]
I would love to see a flow cards added to show:
- Battery status
- Bridge Status / WiFi strength
- Bridge Bluetooth

**Comment by XeroxQ** [comment]
Battery status has a tag (thus, you can use a Logic card for it).
![image](https://github.com/loqed-nl/homey-app/assets/43435060/a691e21c-46da-4e35-a142-afac77f033dd)

**Comment by Petclaud** [comment]
Thx - indeed since end of December the LOQED app (test version) has been updated to carter for this.
