### ISSUE TITLE
Request: pls add flow cards with timeline data

### ISSUE THREAD

**Issue by Petclaud** [loqed-nl/homey-app#27]
Please consider making flow cards available with time line data. E.g. : XYZ has opened the door, to be able to change presence in Homey.

**Comment by XeroxQ** [comment]
![image](https://github.com/loqed-nl/homey-app/assets/43435060/b8d1bfca-e850-4d92-a3e0-58ee38e1465d)

**Comment by XeroxQ** [comment]
You can use this card for it now.

**Comment by Petclaud** [comment]
Thx - indeed since end of December the LOQED app (test version) has been updated to carter for this.
