### ISSUE TITLE
Loqed unlock command from Homey doesnt open the door while the unlock button in the Loqed app does

### ISSUE THREAD

**Issue by calciumdude** [loqed-nl/homey-app#30]
When i open my loqed app on my iphone i only have the option Unlock , when i press this , the door opens and i can go inside.
when i do the same using the unlock command from the homey app it only unlocks the lock and doesnt pull the pin inside, leaving the door closed.
I dont have the option to issue an open command (not available to me in homey)

also i have no way to program the Opening hours (touwtje uit de brievenbus) from inside homey flows.

homey app version  : 3.4.1
ios app version : 2.1.6
Loqed version : 2.6.108
bridge version : 71

**Comment by XeroxQ** [comment]
Does your door has a nop or handle?

**Comment by calciumdude** [comment]
> Does your door has a nop or handle?

little bit of both actually , i have a handle on the outside that isnt moving unless the cylinder is unlocked (have to pull it up to lock it with the anti theft bolts.
but i have configured the lock with a knob.

**Comment by calciumdude** [comment]
> Does your door has a nop or handle?

it strange that the action executed by the lock in the IOS App (only unlock available) that pulls the bolt inside, and back out after.
which isnt the same as the unlock action performed by the homey app ; only does something inside the lock but leaves the bolt untouched.

when i configure the lock with a handle on the outside , i have the option to open the lock but that pulls the bolt inside and leaves it inside, it doesnt return the bolt to its normal position.
so that configuration doesnt work at all

**Comment by calciumdude** [comment]
anything happening on this issue ?
i have some video's on what i mean if that could help.

at this moment the homey integration with the loqed lock is not working for me , 
while i was perfectly happy with it in the past :(

hard to believe i am the only one experiencing this 

current
homey app version : 3.4.6

**Comment by calciumdude** [comment]
solved in 3.4.7 by setting a checkbox to open the door when unlocking ! many thanks !!
