### ISSUE TITLE
Suggestion: report user to Homey 

### ISSUE THREAD

**Issue by ElStupid** [loqed-nl/homey-app#7]
Would like to see in Homey who (which key) opened my door. 
At the moment Loqed only reports to Homey the door is unlocked. When I have a bunch of keys, it's not clear (in Homey) who opened my door

**Comment by hansallis** [comment]
It seems that, if you use the 'lock state changed' trigger instead of the 'lock closed' and 'lock opened' triggers, you do get that information available as a tag! Does that help?

**Comment by ElStupid** [comment]
Yes, found that already. Would like to see it at the other triggers as well, but this works for now

**Comment by BertvanHoekelen** [comment]
It's currently not possible in the Homey sdk to add tags like the user email to the default locked/unlocked flows. So I suggest using the `lock state changed` flow.
